### ISSUE TITLE
Grade E vs F in `row snyk-stages`

### ISSUE THREAD

**Issue by mbiesiad** [snyk/user-docs#147]
Hi,

Not a big deal, but there is some quick fixes to do.
Please feel free to redirect this issue to other repo if needed.

Repro steps:
1. Go to: https://snyk.io/website-scanner/
2. Scroll down to see "HOW IS THE SECURITY SCORE CALCULATED"

[1] There is info about "(...) and the lowest is an **E**", but it is **F**.
[2] Missing spaces for this parts there:
"metric**s:1.** Vulnerable" 
"thre**at.2.** Security"
(before numbers)

Screenshots:
![image](https://user-images.githubusercontent.com/18367606/207725260-518c024f-3ca7-4917-b694-d989a314b1ab.png)
but:
![image](https://user-images.githubusercontent.com/18367606/207725333-7d278f82-58f4-4147-b87a-1675f4328392.png)
and
![image](https://user-images.githubusercontent.com/18367606/207725404-ff043f85-30e1-490b-b3c2-f15d619cffa0.png)

source: https://snyk.io/blog/website-security-score-explained/

Best wishes,

**Comment by david-j-bailey** [comment]
Many thanks Michal - this should be fixed now!

**Comment by mbiesiad** [comment]
My pleasure! That's great 🎉🎉 Best wishes,
