### ISSUE TITLE
ACR Integration for Snyk unclear

### ISSUE THREAD

**Issue by AndersRunningen** [snyk/user-docs#252]
Hi, 

Trying to look at the documentation for [configure-integration-for-acr](https://github.com/snyk/user-docs/blob/main/docs/integrate-with-snyk/snyk-container-integrations/container-security-with-acr-integrate-and-test/configure-integration-for-acr.md), but are strugeling to figure out how we can use a App Registration (Service Principle) when authenticating as it looks like you only describe ACR Admin username and password in the documentation. This will be a bad security configuration from a company like Snyk and are wondering if you could update the documentation to describe how we can use App Registration or maybe if you have any plans for Identity federation? 

Will it be better to sett this up via the kubernetes integration for AKS with Helm [Documentation](https://docs.snyk.io/scan-with-snyk/snyk-container/integrate-with-kubernetes/install-the-snyk-controller/install-the-snyk-controller-with-helm-azure-and-google-cloud-platform)?

**Comment by TashaTBaker** [comment]
Hi,

Thank you for contacting us!

The ACR integration and Kubernetes integration require different setup steps, and we recommend following the steps outlined in our documentation. If you would like to raise this further with Snyk, please contact [Snyk support](https://support.snyk.io/hc/en-us/requests/new).
