### ISSUE TITLE
clarify if --exclude takes a glob or not

### ISSUE THREAD

**Issue by Aghassi** [snyk/user-docs#94]
https://github.com/snyk/user-docs/blob/a2d2bae5866fdd1c7979c76610218555e4ff361a/docs/snyk-cli/commands/monitor.md

According to the docs exclude takes a glob pattern, but the docs say you need to specify all files and folders you don't want. I want to use a glob to say "all folders except folders that have extension type `.xz`". Thus I'd like to use a `glob` to do that. Is that possible?

When I try it I get the following

```sh
+ ../snyk-cli_mac/file/snyk test --all-projects '--exclude=**/!(*.go)'
The --exclude argument must be a comma separated list of directory or file names and cannot contain a path.
```

**Comment by owenmorrill** [comment]
Hey @Aghassi, we're putting this question to our dev team and we'll get the clarification up as soon as we hear back. Thanks for the feedback on this!

**Comment by Aghassi** [comment]
No problem! As far as I can tell it does not work with a glob, but I have in the meantime used glob expansion in bash to construct the logic I need. 


```sh
#!/usr/bin/env bash
shopt -s extglob

# get all directories that don't contain go files from the source tree
cd "$BUILD_WORKING_DIRECTORY"
EXCLUDED_PROJECTS=!(*.go|bazel-*|third-party)
LIST_OF_EXCLUDED_PROJECTS=$(echo $EXCLUDED_PROJECTS | sed 's/ /\n/g')
COMMA_SEPARATED_EXCLUDED_PROJECTS=""
for I in $LIST_OF_EXCLUDED_PROJECTS
do
  if [ -d $I ]; then
    if [ ${#COMMA_SEPARATED_EXCLUDED_PROJECTS} == 0 ]; then
      COMMA_SEPARATED_EXCLUDED_PROJECTS="$I"
    else
      COMMA_SEPARATED_EXCLUDED_PROJECTS="$COMMA_SEPARATED_EXCLUDED_PROJECTS,$I"
    fi
  fi
done
```

Given the above, I can pass the final string to the `--exclude` flag in a bash script. I'm still testing.

**Comment by owenmorrill** [comment]
Hey, we've updated the text here: https://github.com/snyk/user-docs/blob/a2d2bae5866fdd1c7979c76610218555e4ff361a/docs/snyk-cli/commands/monitor.md#--excludeglobglob

**Comment by Aghassi** [comment]
Ok so to clarify then, it never supported taking a `glob` :)
